public enum QuestName
{
    None,
    PerformDiagnostics,
    GettingALayOfTheLand,
    ForGlory,
    WhateverFloatsYourBoat,
    AnIdiotsLuggage,
    KarlTheJarl,
    GoldenHandcuffs,
    ButThisIsMyBirthCertificate,
    InternLunchHour,
    CalculatorCatastrophe,
    ThisIsPureSnow,
    ThingsAreGettingSerious,
    TheGreatWolf,
    BjornAndMoose,
    ForbiddenLovers,
    ForTheUnion,
    TheEnd
}